### ISSUE TITLE
프로필 이미지 요청 API 관련 이슈

### ISSUE THREAD

**Issue by srngch** [team-noir/the-pong#181]
## 구현할 내용

프론트 쪽에서 로그인하고 나면 프로필 이미지를 가져오는 요청이 있습니다.
서버 최초 실행 등의 상황에서 프로필 이미지 디렉토리가 없는 경우 500번대 오류가 납니다.

- related to #171 

## Tasks

- [ ] `/uploads/profile-images` 디렉토리가 있는지 체크하고, 디렉토리 생성하는 코드
- [ ] 존재하지 않는 유저 번호로 이미지를 요청해서 디렉토리가 없는 경우의 예외 처리

**Comment by hhkim0729** [comment]
```
the-pong_backend_dev   | [Nest] 653  - 03/22/2023, 11:20:27 AM   ERROR [ExceptionsHandler] Cannot read properties of null (reading 'split')
the-pong_backend_dev   | TypeError: Cannot read properties of null (reading 'split')
the-pong_backend_dev   |     at UsersService.downloadProfileImage (/usr/src/app/src/api/users/users.service.ts:42:36)
the-pong_backend_dev   |     at UsersController.downloadProfileImage (/usr/src/app/src/api/users/users.controller.ts:33:20)
the-pong_backend_dev   |     at /usr/src/app/.yarn/unplugged/@nestjs-core-virtual-8af2ec411a/node_modules/@nestjs/core/router/router-execution-context.js:46:28
the-pong_backend_dev   |     at /usr/src/app/.yarn/unplugged/@nestjs-core-virtual-8af2ec411a/node_modules/@nestjs/core/router/router-proxy.js:9:17
the-pong_backend_dev   | Error: ENOENT: no such file or directory, open '/usr/src/app/upload/profile-images/null'
```
