### ISSUE TITLE
oauth 로그인 관련

### ISSUE THREAD

**Issue by srngch** [team-noir/the-pong#270]
## 구현할 내용

우선순위 낮습니다..

A기기로 로그인 한적이 있는 계정으로 B기기에서 로그인 했을 때 에러 로그

```shell
the-pong_backend_dev   | [Nest] 496  - 04/05/2023, 4:41:32 PM   ERROR [ExceptionsHandler] Failed to obtain access token
the-pong_backend_dev   | InternalOAuthError: Failed to obtain access token
the-pong_backend_dev   |     at FTStrategy.OAuth2Strategy._createOAuthError (/usr/src/app/.yarn/cache/passport-oauth2-npm-1.7.0-5a29a31e32-9e93f1f47a.zip/node_modules/passport-oauth2/lib/strategy.js:423:17)
the-pong_backend_dev   |     at /usr/src/app/.yarn/cache/passport-oauth2-npm-1.7.0-5a29a31e32-9e93f1f47a.zip/node_modules/passport-oauth2/lib/strategy.js:177:45
the-pong_backend_dev   |     at /usr/src/app/.yarn/cache/oauth-npm-0.9.15-a6aae972bc-957c0d8d85.zip/node_modules/oauth/lib/oauth2.js:191:18
the-pong_backend_dev   |     at ClientRequest.<anonymous> (/usr/src/app/.yarn/cache/oauth-npm-0.9.15-a6aae972bc-957c0d8d85.zip/node_modules/oauth/lib/oauth2.js:162:5)
the-pong_backend_dev   |     at ClientRequest.emit (node:events:512:28)
the-pong_backend_dev   |     at TLSSocket.socketErrorListener (node:_http_client:495:9)
the-pong_backend_dev   |     at TLSSocket.emit (node:events:512:28)
the-pong_backend_dev   |     at emitErrorNT (node:internal/streams/destroy:151:8)
the-pong_backend_dev   |     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
the-pong_backend_dev   |     at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by PCHANUL** [comment]
'FTStrategy'를 더 이상 사용하지 않으므로 이슈를 닫습니다.
