### ISSUE TITLE
도커와 VM 관련 설정

### ISSUE THREAD

**Issue by srngch** [team-noir/the-pong#391]
## 구현할 내용

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by srngch** [comment]
### backend 컨테이너 unplugged
```
backend_dev   | /usr/src/app/.pnp.cjs:19241
backend_dev   |   return Object.defineProperties(new Error(message), {
backend_dev   |                                  ^
backend_dev   |
backend_dev   | Error: Required unplugged package missing from disk. This may happen when switching branches without running installs (unplugged packages must be fully materialized on disk to work).
backend_dev   |
backend_dev   | Missing package: yarn@npm:1.22.19
backend_dev   | Expected package location: /usr/src/app/.yarn/unplugged/yarn-npm-1.22.19-6ba13b96dc/node_modules/yarn/
backend_dev   |
backend_dev   |     at makeError (/usr/src/app/.pnp.cjs:19241:34)
backend_dev   |     at resolveUnqualified (/usr/src/app/.pnp.cjs:21045:17)
backend_dev   |     at resolveRequest (/usr/src/app/.pnp.cjs:21097:14)
backend_dev   |     at Object.resolveRequest (/usr/src/app/.pnp.cjs:21153:26)
backend_dev   |     at resolve$1 (file:///usr/src/app/.pnp.loader.mjs:1991:25)
backend_dev   |     at nextResolve (node:internal/modules/esm/loader:163:28)
backend_dev   |     at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
backend_dev   |     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
backend_dev   |     at ESMLoader.import (node:internal/modules/esm/loader:525:22)
backend_dev   |     at node:internal/modules/run_main:58:28
```
