### ISSUE TITLE
oauth 로그인 오류

### ISSUE THREAD

**Issue by srngch** [team-noir/the-pong#553]
## 구현할 내용

<img width="711" alt="image" src="https://github.com/team-noir/the-pong/assets/85778562/1e4a0af1-8547-465b-9d20-09d10629b60c">

```
the-pong_nginx_dev     | 172.18.0.1 - - [17/May/2023:16:03:31 +0900] "GET /api/v1/auth/42/return?code=e314d9deb8be70789bcb391016b01eaee28edaeafadd4ab581fff2e1968a4fb0 HTTP/1.1" 500 52 "http://localhost:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" "-"
the-pong_backend_dev   | [Nest] 891  - 05/17/2023, 7:03:31 AM   ERROR [ExceptionsHandler] Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
the-pong_backend_dev   | TokenError: Client authentication failed due to unknown client, no client authentication included, or unsupported authentication method.
the-pong_backend_dev   |     at FTStrategy.OAuth2Strategy.parseErrorResponse (/usr/src/app/.yarn/cache/passport-oauth2-npm-1.7.0-5a29a31e32-9e93f1f47a.zip/node_modules/passport-oauth2/lib/strategy.js:373:12)
the-pong_backend_dev   |     at FTStrategy.OAuth2Strategy._createOAuthError (/usr/src/app/.yarn/cache/passport-oauth2-npm-1.7.0-5a29a31e32-9e93f1f47a.zip/node_modules/passport-oauth2/lib/strategy.js:420:16)
the-pong_backend_dev   |     at /usr/src/app/.yarn/cache/passport-oauth2-npm-1.7.0-5a29a31e32-9e93f1f47a.zip/node_modules/passport-oauth2/lib/strategy.js:177:45
the-pong_backend_dev   |     at /usr/src/app/.yarn/cache/oauth-npm-0.9.15-a6aae972bc-957c0d8d85.zip/node_modules/oauth/lib/oauth2.js:191:18
the-pong_backend_dev   |     at passBackControl (/usr/src/app/.yarn/cache/oauth-npm-0.9.15-a6aae972bc-957c0d8d85.zip/node_modules/oauth/lib/oauth2.js:132:9)
the-pong_backend_dev   |     at IncomingMessage.<anonymous> (/usr/src/app/.yarn/cache/oauth-npm-0.9.15-a6aae972bc-957c0d8d85.zip/node_modules/oauth/lib/oauth2.js:157:7)
the-pong_backend_dev   |     at IncomingMessage.emit (node:events:525:35)
the-pong_backend_dev   |     at endReadableNT (node:internal/streams/readable:1359:12)
the-pong_backend_dev   |     at processTicksAndRejections (node:internal/process/task_queues:82:21)

```

**Comment by srngch** [comment]
stale: 더 이상 42Oauth를 사용하지 않음
